export const BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? 'http://127.0.0.1:3000';

export const CATEGORIES: string[] = [
  'Amenities', 'Amusement Park', 'Boutique', 'Branded Plotted Development',
  'Business Centers', 'Campus Design', 'Club', 'Co-Working Facilities',
  'Commercial & Retail', 'Commercial Mixed-Use', 'Compact Housing', 'Competition winner',
  'Data Centers', 'Facade', 'Game Zone', 'Govt. Aspiration Houses',
  'Green Buildings', 'Healthcare', 'High Density Residential', 'High-Rise',
  'Hospitals', 'Hotel & Hospitality', 'Hotels', 'I-Euro & Social',
  'Iconic', 'Ideas', 'Incubation Center', 'Infrastructure', 'Institution',
  'Interiors', 'IT Parks', 'Large Scale Development', 'Large Scale Integrated Township',
  'Large Scale Master Planning', 'Luxury Housing', 'Master Planning & Urban Design',
  'Mixed-Use', 'Naturopathy', 'Outdoor Stadium', 'Podium Top Garden', 'Recreation',
  'Redevelopment', 'Rehabilitation Center', 'Research & Development Center',
  'Research & Diagnostic Center', 'Residential', 'Resort', 'Rooftop Garden', 'School',
  'SEZ', 'Skyscrapers', 'Social Housing', 'Sports', 'Sports City', 'Sports Club',
  'SRA', 'Stadium', 'Sustainable', 'Tourism', 'Training Center', 'University',
  'Urban Design', 'Vastu Housing', 'Villa', 'Waterfront', 'Workplaces',
];

export const PAGE_PROJECTS: Record<number, string[]> = {
  23: ['The Promenade by the River'],
  24: ['Where Structure Meets Expression'],
  29: ['Efficient Luxury'],
  34: ['A Crescent That Shaped a Neighbourhood'],
  35: ['Layered Luxury'],
  39: ['Social Housing'],
  43: ['Green Airy'],
  45: ['Courtyard'],
  46: ['The Fluid Urban Grandeur'],
  50: ['The Vibrant Urban Promenade'],
  53: ['The Cascade'],
  54: ['In Density'],
  56: ['Rene'],
  58: ['Arial Panorama From Podium'],
  60: ['Mingling Gardens'],
  61: ['Meets the City', 'Refined.'],
  63: ['The Sea Towers'],
  66: ['Royal Living On the 18th Hole'],
  68: ['Urban Green Gateway'],
  69: ['Sun and Sand Ultra Luxury Residential Development'],
  70: ['Stepping Sky Villas'],
  71: ['Rising High'],
  72: ['High Tide'],
  73: ['The True Net Zero'],
  75: ['The Crown of the Arabian Sea'],
  76: ['The Pinnacle of Coral Grandeur'],
  77: ['Sea Deck'],
  78: ['Green Heaven'],
  79: ['Aspiring & Efficient'],
  81: ['Aakisa', 'Ocean Front'],
  82: ['Pentagon', 'The Sky'],
  83: ['The Cornerstone'],
  85: ['The Urban Eye'],
  87: ['The Citadel'],
  88: ['Sleek and Slender', 'The Art of Living'],
  89: ['Three Side Panorama'],
  90: ['The Y'],
  92: ['Living Within Interlaced Clusters.'],
  93: ['The Fantastic Trio'],
  94: ['Musketeers'],
  96: ['Rejuvenating'],
  97: ['Skyline'],
  98: ['Community'],
  100: ['Compromise.'],
  101: ['Competitive'],
  102: ['The Orchard', 'The Vibrant Podium'],
  104: ['Designed For Tomorrow'],
  105: ['Theiconsof Gorai Premium Redevelopment at Borivali'],
  106: ['Landmark. Not Just Address.'],
  107: ['The High Gardens'],
  108: ['A Responsive Facade', 'Lost In Forest Premium Gardlen Housing Project', 'Maximise Views and Environmental Comfort. the Planning Integrates Open Spaces.'],
  109: ['Shielded. Oriented. Elevated.', 'The Serenity'],
  110: ['Living In Plus'],
  111: ['Democratizing Suburban Elegance'],
  112: ['Elevated Living', 'Utopian Twins'],
  113: ['Efficiency In Density'],
  114: ['Forest', 'Kohinoor'],
  115: ['Neo Modern', 'Tree Redevlopment at Bhayandar'],
  116: ['From Address To Destination Iconic Luxurious Residential Sky Scrapper at Worli'],
  117: ['Luxury & Prestige', 'Ridge'],
  118: ['Mango Zara'],
  119: ['A Sky Pool', 'One Tower. Total Resolve'],
  120: ['Sky Scrapers', 'The Pencil Tower'],
  121: ['The Vertical Oasis'],
  122: ['Bridging Eras, Elevating Lifestyles'],
  123: ['Linear and Minimal', 'Step On the Roof'],
  124: ['Overlooking the Greens', 'Shahad Tower', 'Urban Footprint'],
  125: ['The Sky'],
  126: ['of Island City'],
  127: ['Low-rise Elegance', 'Skyline'],
  128: ['A Timeless Twin', 'The Oculus Premium Terrace Housing'],
  129: ['The Green Envelope'],
  130: ['The Art Deco Icon', 'The Life After SRA'],
  131: ['Orchestrated As One', 'The Upper Deck'],
  132: ['Exclusivity', 'The Rising Waves'],
  133: ['Community', 'For Inclusive Density', 'Rising From the Ashes'],
  134: ['Elegance Through Art Deco', 'The C Community'],
  135: ['Dignity Homes', 'Epitome of Luxury', 'Scorpio- An Iconic Tower'],
  136: ['Beyond Architecture'],
  137: ['Round the Corner', 'The Petals'],
  138: ['Blue Needle', 'Warm Authority'],
  139: ['The Curved Horizon', 'The Faceted Crown'],
  140: ['Reframing Urbanity', 'Sea Breeze', 'The Urban Loft'],
  141: ['Suburban Luxe', 'The Twin Towers'],
  142: ['Green Rooftops'],
  143: ['The Collective Decks'],
  144: ['The Flaming'],
  145: ['The Hanging Gardens', 'The Magic of Plus', 'The Urban Crescent'],
  147: ['Contours In Motion High Rise Residential'],
  148: ['Fairway Living'],
  149: ['Streets With a Character', 'The Social Spine'],
  150: ['Gateway', 'The C Shape Courtyard'],
  153: ['The New Gateway of India'],
  154: ['OB + G + OP + 18max', 'The Virgin Islands'],
  155: ['The Urban Rejuvenation'],
  157: ['For the Masses'],
  158: ['The Nation\'s Pride'],
  162: ['Stitching the Contours'],
  164: ['Sculpted by Nature'],
  166: ['Living'],
  167: ['Glass'],
  168: ['Elegance'],
  169: ['The Island of Manor', 'Tropical Retreat'],
  170: ['A New Address On the World Map'],
  171: ['Curves In Harmony', 'Gopinath Villa', 'Mediterranean Retreat'],
  172: ['Hanging Gardens of Panchagni', 'The Green Spine'],
  175: ['Where Glass Meets Grid Premium Iconic Office Tower at Goregaon'],
  176: ['Genius Loci'],
  177: ['Curves Above, Life Below'],
  178: ['The Secret of Unicorn'],
  180: ['Sky Deck', 'Urban Vivacity'],
  181: ['The Corporate Forest'],
  183: ['Chambers', 'Garden Edge Office'],
  185: ['Books&musicstore'],
  188: ['Green Building'],
  189: ['The Sloping Tranquility'],
  190: ['Skyline In Gold', 'The Curve'],
  191: ['A Diagrid of Light and Power'],
  192: ['The Rhythm In Glass', 'The Solar Facade'],
  193: ['Vibrant Workplace'],
  194: ['A Linear Approach'],
  195: ['Luxury Edges'],
  196: ['Green Building'],
  197: ['Gateway', 'Sustainable Eco System'],
  198: ['Efficiency', 'Vsg Legacy'],
  199: ['Geometry', 'The Spinning Tower'],
  200: ['Sunand Shade'],
  201: ['The Cascading Mall'],
  202: ['Green Fluidity', 'The Forest'],
  203: ['The Spacecraft'],
  204: ['Decks Boutique Green Office Building at Baner'],
  205: ['Shaded by Design', 'The Curvy Edge'],
  206: ['BMW Auto Hangar at Andheri, Mumbai', 'The Bold and Beautiful', 'The Kinetic Energy'],
  207: ['Daga Palazzo'],
  208: ['The Revealing Gardens'],
  209: ['The Expressive Block'],
  210: ['Speaking Facade', 'The Porous'],
  211: ['Green Break Better Work', 'Modularityfor Scalability'],
  212: ['Manhattan', 'The Rhythm'],
  215: ['Serenity In Terraces'],
  216: ['Skyline From the Balcony', 'The Tale of Two Facades'],
  217: ['From Feather To Form'],
  218: ['A Modern, Rustic Retreat'],
  219: ['of Learning and Innovation'],
  220: ['The Eden Courtyard'],
  221: ['The Urban Sanctuary'],
  222: ['Sea Deco', 'Structured Living', 'Where Luxury Flows Across Every Tier'],
  223: ['Corporate Cluster'],
  224: ['Built To Heal.', 'of Elegance'],
  226: ['An Escape', 'The Club of Distinction'],
  227: ['Opulence In Desert', 'The Sailing Yacht'],
  228: ['Business Oval Expression Businesshotelat Vijayawada', 'Efficiency', 'Rising Waves'],
  229: ['Club Regency at Chennqi', 'Flows'],
  230: ['Art Gallery & Club'],
  231: ['From Parking To Park'],
  232: ['The Golden Flute'],
  233: ['Island of Bliss', 'The Grand Entry Club at Mumbai (Design Option)', 'The Rooftop Stadium'],
  234: ['Shanghai Home', 'The Inner Connection', 'Thermal Comfort and Collective Well-being.'],
  235: ['His Highness', 'Landscape Flow Naturally Together.', 'Resort at Pirangut', 'Tailored Elegance', 'Timeless Lotus', 'Vedic Village at Karjat'],
  236: ['Business Service Apartments', 'Luxury'],
  237: ['Elegance', 'Maldives'],
  238: ['Exclusive and Elegant'],
  239: ['Ruby'],
  240: ['A Warm Welcome', 'Handsome', 'Lifestyle Club', 'Linear Light'],
  242: ['Begin To Heal'],
  243: ['Design.', 'Instilling Facade'],
  244: ['Archives', 'Hospital-1', 'Hospital-2'],
  247: ['Maharail Railway Station'],
  248: ['Nasik Road Railway Station'],
  249: ['Pune Railway Station', 'The Logistics'],
  250: ['The Blooming Transit Hub'],
  251: ['A World-class Aerocity', 'Organic, Fluid Form a Deliberate Counterpoint To the Disciplined Commercial Blocks', 'The 4PL Hub', 'The Cloud'],
  252: ['Intermodal Core Bharuch'],
  253: ['Factory, Reimagined Industrialfacilityat Khedcity', 'Shahad'],
  255: ['The Urban Cricket Bowl'],
  256: ['Beyond the Finish Line', 'Every Approach.the Facade Language Draws From the'],
  257: ['Howzat!!', 'Play On'],
  258: ['Journey', 'The Modern Akhada'],
  261: ['The Stepping'],
  263: ['Development Park'],
  264: ['The Responsive Greenroofs'],
  265: ['of Philosophy'],
  267: ['Ridge'],
  268: ['The Gateway To Courtyard', 'The Inclusive Roof'],
  269: ['of Learning'],
  270: ['Open and Porous'],
  272: ['The Dome of Knowledge'],
  273: ['Learning Ecosystems', 'The Garden'],
  274: ['Beyond Education', 'University at Manesar'],
  275: ['Campuses', 'Curiosity', 'Knowledge Park'],
  276: ['The Learning Curve'],
  277: ['Knowledge'],
  279: ['To Inspire'],
  280: ['Over the Edge'],
  281: ['Gardens', 'The Freedom'],
  282: ['Fueling India\'s Industrial Growth'],
  289: ['Grass-root Level', 'The Foundationof Growth'],
};

export const PAGE_NUMBERS: number[] = Object.keys(PAGE_PROJECTS).map(Number).sort((a, b) => a - b);

export const FIRST_PAGE = PAGE_NUMBERS[0];
export const LAST_PAGE = PAGE_NUMBERS[PAGE_NUMBERS.length - 1];
export const TOTAL_PAGES = PAGE_NUMBERS.length;

export const MULTI_PROJECT_PAGE_2 = 61;
export const MULTI_PROJECT_PAGE_3 = 108;
export const MULTI_PROJECT_PAGE_6 = 235;
